---
  - name: install tomcat on ubuntu
    become: true
    hosts: tomcat
    tasks:
      - name: check playbook is being executed on supported os
        ansible.builtin.fail:
          msg: "This playbook is designed for ubuntu only"
        when: ansible_facts['distribution'] != "Ubuntu"
      - name: install java
        ansible.builtin.apt:
          name: "{{ java_package }}"
          update_cache: true
          state: present
      - name: create group
        ansible.builtin.group:
          name: "{{ group }}"
          state: present
      - name: create user tomcat
        ansible.builtin.user:
          name: "{{ user }}"
          create_home: yes
          home: "{{ homedir }}"
          shell: "{{ shell }}"
          group: "{{ group }}"
      - name: download tomcat
        ansible.builtin.get_url: 
          url: "https://www-eu.apache.org/dist/tomcat/tomcat-{{ tomcat_major_version}}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
          dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
      - name: extract the tomcat
        ansible.builtin.unarchive:  
          src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz" 
          dest: "{{ homedir }}"
          remote_src: yes 
      - name: create a symblic link
        ansible.builtin.file:
          src: "{{ homedir }}/apache-tomcat-{{ tomcat_version }}"
          dest: "{{ homedir }}/latest"
          state: link
      - name: change ownership to tomcat
        ansible.builtin.file:
          path: "{{ homedir }}"
          state: directory
          recurse: yes
          owner: "{{ user }}"
          group: "{{ group }}"
