---
- name: install apache2 
  hosts: all
  become: yes
  task:
    - name: install apt update & install apt install apache2
      apt: 
        name: apache2
        state: present
        update_cache: yes

---

---
- name: install apache2
  hosts: all
  become: yes

  tasks:
    - name: install apt update & install apt install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
