---
- name: tree
  host: all
  become: yes
  task: 
    -name: update packeg and install tree
     apt:
       name: tree
       state: present
       update_cache: yes


  ---
- name: hello ansible
  hosts: all
  become: yes
  tasks:
    - name: update packages and install tree
      apt:
        name: tree
        state: present
        update_cache: yes