---
- name: install lamp server on redhat
  hosts: redhat
  become: true
  tasks:
    - name: install httpd on server
      ansible.builtin.yum:
        name: httpd
        update_cache: true
        state: present
    - name: start httpd service and enable
      ansible.builtin.systemd:
        name: httpd
        enabled: true
        state: started
      notify:
        - restart httpd
    - name: install php server
      ansible.builtin.yum:
        name: php
        update_cache: true
        state: present
      notify:
        - restart httpd
    - name: start httpd service and enable
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
        state: started 
    - name: copy info.php page
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify:
        - restart httpd
  handlers:      
    - name: restart httpd service 
      ansible.builtin.systemd:
        name: httpd
        state: restarted