---
- name: install apache2 
  hosts: all
  become: yes
  task:
    - name: install apt update & install apt install apache2
      apt: 
        name: apache2  ->>> isntead of these - {{ package }}
        state: present
        update_cache: yes

---

---
- name: install apache2
  hosts: all
  become: yes
  tasks:
    - name: install apt update & install apt install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

---  
- name: hello ansible
  hosts: all
  become: yes
  tasks:
    - name: update package and install tree
      ansible.builtin.apt:
        name: tree
        state: present
        update_cache: yes 

---

