---
  - name: install lamp server on ubuntu
    hosts: all
    become: yes
    tasks:
      - name: install apache server
        ansible.builtin.apt:
          name: apache2
          update_cache: true
          state: present
      - name: install php packages
        ansible.builtin.apt:
          name:
            - php
            - lib