---
  - name: installation of spring pet clinic
    become: yes
    hosts: all  
    tasks: 
      - name: installing java
        ansible.builtin.apt:
          name: openjdk-11-jdk
          state: present
          update_cache: yes
      - name: download spring petclinic
        ansible.builtin.get_url:
          url: "https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar"
          dest: "/home/spring-petclinic-2.4.2.jar"
      - name: extract springpetclinic
        ansible.builtin.unarchive:
          src: "/spring-petclinic-2.4.2.jar"
          dest: "/home/ubuntu"
          remote_src: yes