---
- name: install Nop Commerce on ubuntu
  hosts: ubuntu
  become: true
  tasks:
    - name: download debian packages
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /home/ubuntu
    - name: install debian package 
      ansible.builtin.apt:
        deb: /home/ubuntu/packages-microsoft-prod.deb
    - name: install dotnet 7
      ansible.builtin.apt:
        name: dotnet-sdk-7.0
        state: present
        update_cache: true
    - name: Add the user nopCommerce with a primary group of nopCommerce
      ansible.builtin.user:
        name: nopCommerce
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/nopCommerce
        state: directory
    - name: installing unzip for nop zip file
      ansible.builtin.apt:
        name: unzip
        update_cache: yes
        state: present
    - name: download nopCommerce zipfile 
      ansible.builtin.get_url: 
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.3/nopCommerce_4.60.3_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
    - name: Unzip file nopCommerce zipfile
      ansible.builtin.unarchive:
        src: /var/www/nopCommerce/nopCommerce_4.60.3_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce/
        remote_src: yes
    - name: Create  bin folder logs folder 
      ansible.builtin.file:
        path:
          - /var/www/nopCommerce/bin
          - /var/www/nopCommerce/logs
        state: directory
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/www/nopCommerce
        owner: nopCommerce
        group: nopCommerce
        mode: '0777'
        state: directory
        recurse: true
    - name: Copy nop service file to nopcommerce path
      ansible.builtin.copy:
        src: nopCommerce.service
        dest: /etc/systemd/system/nopCommerce.service
    - name: Start service nopCommerce, if not started
      ansible.builtin.service:
        name: nopCommerce
        enabled: true
        state: started